### ISSUE TITLE
Updated NuGet Package

### ISSUE THREAD

**Issue by bbenetskyy** [lettucebo/Ci.Sort#3]
Hi,

I'm need to use new changes in my project.
Could you publish new NuGet package and close this issue?

Thank you))))

**Comment by lettucebo** [comment]
Sorry, my bad, I forgot publish nuget package
I have publish the package, unfortunately the nuget current is down..
You can try new package after nuget service restore

![nuget](https://user-images.githubusercontent.com/891383/37763275-904060cc-2df9-11e8-8426-81f2a7e4ea6f.png)

**Comment by bbenetskyy** [comment]
Okey, I will try it tomorrow, and if all going fine - close this Issue.

**Comment by lettucebo** [comment]
Hi

I have publish a new version 1.1.1 to include your pull request

**Comment by bbenetskyy** [comment]
:ok_hand: Works perfectly
